# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy on Release

on:
  release:
    types: [published]

jobs:
  build-mac:
    strategy:
      matrix:
        platform: [macos-latest,windows-latest]
    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn

    - name: Bump Version
      run: |
        echo ${{ github.ref_name }}
        npm pkg set version=${{ github.ref_name }}
    
    - name: Package App
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn package
